import { createHash } from "node:crypto";
export class ReviewerRuntimeError extends Error { constructor(code, message, details = {}) { super(message); this.name = "ReviewerRuntimeError"; this.code = code; this.details = Object.freeze(structuredClone(details)); } }
export function canonicalJson(value) { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(",")}}`; return JSON.stringify(value); }
export const digest = (value) => createHash("sha256").update(canonicalJson(value)).digest("hex");
const SHA = /^[0-9a-f]{64}$/;
const record = (v, l) => { if (!v || Array.isArray(v) || typeof v !== "object") throw new ReviewerRuntimeError("invalid_contract", `${l} must be an object`); return v; };
const text = (v, l) => { if (typeof v !== "string" || !v.trim()) throw new ReviewerRuntimeError("invalid_contract", `${l} must be non-empty text`); return v; };
const exact = (v, fields, l) => { record(v, l); const s = new Set(fields); if (Object.keys(v).some((k) => !s.has(k)) || fields.some((k) => !(k in v))) throw new ReviewerRuntimeError("invalid_contract", `${l} fields are invalid`); };
const strings = (v, l, required = false) => { if (!Array.isArray(v) || (required && !v.length) || v.some((x) => typeof x !== "string" || !x.trim()) || new Set(v).size !== v.length) throw new ReviewerRuntimeError("invalid_contract", `${l} is invalid`); };
const sha = (v, l) => { if (typeof v !== "string" || !SHA.test(v)) throw new ReviewerRuntimeError("invalid_contract", `${l} must be lowercase SHA-256`); };
export function validateReviewerProfile(v) { exact(v, ["schemaVersion","profileId","enabled","requestedModel","provider","reasoning","capabilities","outputSchema","effectiveInstructions","isolatedHome","limitations","acceptingAuthority","configurationDigest"], "reviewer profile"); if (v.schemaVersion !== 1 || typeof v.enabled !== "boolean" || v.isolatedHome !== true) throw new ReviewerRuntimeError("configuration", "reviewer profile flags are invalid"); for (const k of ["profileId","requestedModel","provider","reasoning","outputSchema","effectiveInstructions","acceptingAuthority"]) text(v[k], `profile.${k}`); strings(v.capabilities, "profile.capabilities", true); strings(v.limitations, "profile.limitations"); sha(v.configurationDigest, "profile.configurationDigest"); const c = {...v}; delete c.configurationDigest; if (digest(c) !== v.configurationDigest) throw new ReviewerRuntimeError("configuration", "reviewer profile configuration digest does not match"); return v; }
export function validateCatalogProjection(v) { exact(v, ["schemaVersion","catalogId","observedAt","expiresAt","source","sourceSha256","models"], "catalog projection"); if (v.schemaVersion !== 1) throw new ReviewerRuntimeError("catalog", "catalog schema is invalid"); for (const k of ["catalogId","observedAt","expiresAt","source"]) text(v[k], `catalog.${k}`); sha(v.sourceSha256, "catalog.sourceSha256"); if (!Array.isArray(v.models) || !v.models.length || !Number.isFinite(Date.parse(v.observedAt)) || Date.parse(v.expiresAt) <= Date.parse(v.observedAt)) throw new ReviewerRuntimeError("catalog", "catalog content or freshness interval is invalid"); for (const m of v.models) { exact(m, ["slug","provider","capabilities","routingConstraints"], "catalog model"); text(m.slug,"catalog model slug"); text(m.provider,"catalog model provider"); strings(m.capabilities,"catalog capabilities"); strings(m.routingConstraints,"catalog constraints"); } return v; }
export function validateRawEventPolicy(v) { exact(v, ["classification","access","retention","exactRetentionAuthorized","redaction","tamperEvidence"], "raw event policy"); for (const k of ["classification","access","retention","redaction","tamperEvidence"]) text(v[k], `raw policy.${k}`); if (typeof v.exactRetentionAuthorized !== "boolean") throw new ReviewerRuntimeError("invalid_contract", "raw policy authorization is invalid"); return v; }
export function validateExecutionReceipt(v) { exact(v, ["schemaVersion","attemptId","profileId","profileConfigurationDigest","subjectDigest","catalog","configured","observed","isolation","transport","rawEvidence","failure","result"], "execution receipt"); if (v.schemaVersion !== 1) throw new ReviewerRuntimeError("invalid_contract", "execution schema is invalid"); text(v.attemptId,"receipt attempt"); text(v.profileId,"receipt profile"); text(v.subjectDigest,"receipt subject"); sha(v.profileConfigurationDigest,"receipt profile digest"); for (const k of ["catalog","configured","observed","isolation","transport","rawEvidence"]) record(v[k], `receipt.${k}`); if (v.failure !== null) { exact(v.failure,["kind","message"],"receipt failure"); text(v.failure.kind,"failure kind"); text(v.failure.message,"failure message"); } return v; }
