import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { ExperimentalReviewBenchService, ReviewBenchError, inventoryReviewBenchHistory } from "../../../src/index.mjs";

const ROOT=path.resolve(new URL("../../../..",import.meta.url).pathname), FIXTURES=path.join(ROOT,"skills/review-bench/tests/fixtures");
const json=async(relative)=>JSON.parse(await readFile(path.join(FIXTURES,relative),"utf8"));

test("validates closed artifacts and fails closed on unknown fields and stale snapshots",async()=>{const service=new ExperimentalReviewBenchService(),corpus=await json("corpus.json"),truth=await json("truth.json"),result=await json("results/claude-defect.json"),scoring=await json("scoring/claude-defect.json");assert.deepEqual(service.validate({corpus,truth,result,scoring}),{status:"valid",bench_id:"fixture-bench",experimental:true,production_review_authority:false});const unknown=structuredClone(corpus);unknown.cases[0].historical_finding="leak";assert.throws(()=>service.validate({corpus:unknown}),ReviewBenchError);const stale=structuredClone(result);stale.snapshot_digest="f".repeat(64);assert.throws(()=>service.validate({corpus,result:stale}),/snapshot_digest/);});

test("renders a blinded packet and protocol-specific output contract",async()=>{const service=new ExperimentalReviewBenchService(),corpus=await json("corpus.json"),v1=service.renderCase({corpus,caseId:"defective-state"});assert.equal(v1.packet.case.snapshot.digest,"a".repeat(64));assert.doesNotMatch(JSON.stringify(v1.packet),/identity-replaced/);assert.doesNotMatch(v1.prompt,/stale-mutates/);assert.match(v1.prompt,/review_bench_result_v1/);const v12=structuredClone(corpus);v12.protocol.version="1.2";assert.match(service.renderCase({corpus:v12,caseId:"clean-closure"}).prompt,/verified_claims/);});

test("inventory consumes supplied observations without scanning session stores",()=>{const rows=[{run_id:"run-1",slice_number:1,slice_title:"fixture",status:"accepted",review_findings:{high:1},task_owned_files:["src/state.py"],worker_metrics:{review_gate_calls:1,review_fix_iterations:1,additional_metrics:{workspace:{head:"abc123"}}}},{run_id:"run-1",slice_number:2,slice_title:"forensic",status:"accepted",task_owned_files:["src/other.py"],worker_metrics:{review_gate_calls:1,review_fix_iterations:0}}];const inventory=inventoryReviewBenchHistory(rows,{"run-1":[{path:"/sessions/one.jsonl",agent_path:"/root/run_slice1"},{path:"/sessions/two.jsonl",agent_path:"/root/run_slice2"}]});assert.equal(inventory.status,"provisional_inventory");assert.equal(inventory.candidates[0].reconstruction_state,"partial");assert.deepEqual(inventory.candidates.map((x)=>x.codex_session_candidates.length),[1,1]);assert.deepEqual(new Set(inventory.candidates.map((x)=>x.session_match_quality)),new Set(["run_and_slice"]));});

test("result v2 separates verified claims and observations from findings",async()=>{const service=new ExperimentalReviewBenchService(),corpus=await json("corpus.json"),result=await json("results/claude-clean.json");result.artifact_type="review_bench_result_v2";result.schema_version=2;result.reviewer.review_protocol="evidence-calibrated-review/1.2";result.verified_claims=[{claim_id:"V1",claim:"The repair is established.",evidence:["Focused evidence."],confidence:"high",acceptance_criteria:["Both regressions are covered and production behavior is corrected."]}];result.observations=[{observation_id:"O1",category:"documentation",claim:"One example could be clearer.",evidence:["Direct source."],confidence:"high"}];assert.equal(service.validate({corpus,result}).status,"valid");result.verified_claims[0].confidence="medium";assert.throws(()=>service.validate({corpus,result}),/must be high/);});
