export const REVIEW_BENCH_SCHEMA_VERSION = 1;
export const REVIEW_BENCH_VERDICTS = Object.freeze(["accepted", "rejected", "blocked_unverified", "stale_snapshot"]);
export const REVIEW_BENCH_SEVERITIES = Object.freeze(["critical", "high", "medium", "low"]);
export const REVIEW_BENCH_CONFIDENCE = Object.freeze(["high", "medium", "low"]);

const SETS = {
  verdict: new Set(REVIEW_BENCH_VERDICTS), severity: new Set(REVIEW_BENCH_SEVERITIES), confidence: new Set(REVIEW_BENCH_CONFIDENCE),
  reviewClass: new Set(["placement", "implementation", "closure", "integrity", "visual", "security"]),
  routeClass: new Set(["deterministic_local", "runtime_cross_boundary", "persistent_state_identity_integrity", "novel_architecture_high_consequence"]),
  domain: new Set(["architecture", "configuration", "identity", "integrity", "lifecycle", "performance", "persistence", "runtime", "schema", "security", "tests_docs", "ui_visual", "other"]),
  topology: new Set(["local", "cross_module", "cross_process", "migration", "generated", "concurrency_sensitive", "large_diff"]),
  novelty: new Set(["established_pattern", "pattern_extension", "new_ownership"]),
  evidence: new Set(["static_source", "deterministic_test", "runtime_inspection", "persisted_artifact", "visual_inspection", "human_judgment", "historical_reconstruction"]),
  consequence: new Set(["cosmetic", "recoverable", "workflow_blocking", "state_corrupting", "security_sensitive", "irreversible"]),
  reasoning: new Set(["low", "medium", "high", "xhigh", "max", "ultra", "unknown", "not_configurable"]),
  aggregation: new Set(["none", "self_aggregation", "cross_model_aggregation", "evidence_grounded_aggregation"]),
  risk: new Set(["low", "medium", "high", "critical"]),
  snapshotKind: new Set(["git_commit", "checkpoint", "reconstructed"]),
  reconstruction: new Set(["high", "medium", "low", "unknown"]),
  disposition: new Set(["true_positive", "false_positive", "duplicate", "nonblocking_observation"]),
};

export class ReviewBenchError extends Error {
  constructor(message) { super(message); this.name = "ReviewBenchError"; }
}
export function requireBench(condition, message) { if (!condition) throw new ReviewBenchError(message); }
export function benchRecord(value, path) { requireBench(value && !Array.isArray(value) && typeof value === "object", `${path} must be an object`); return value; }
export function benchArray(value, path) { requireBench(Array.isArray(value), `${path} must be an array`); return value; }
export function benchText(value, path) { requireBench(typeof value === "string" && value.trim(), `${path} must be a nonempty string`); return value; }
export function benchBoolean(value, path) { requireBench(typeof value === "boolean", `${path} must be boolean`); return value; }
export function benchNumber(value, path) { requireBench(typeof value === "number" && Number.isFinite(value) && value >= 0, `${path} must be nonnegative`); return value; }
export function benchInteger(value, path) { requireBench(Number.isSafeInteger(value) && value > 0, `${path} must be a positive integer`); return value; }
export function benchExact(value, required, optional, path) {
  benchRecord(value, path); const keys = new Set(Object.keys(value));
  const missing = required.filter((key) => !keys.has(key));
  const unknown = [...keys].filter((key) => !required.includes(key) && !optional.includes(key));
  requireBench(!missing.length, `${path} missing fields: ${missing.sort().join(", ")}`);
  requireBench(!unknown.length, `${path} unknown fields: ${unknown.sort().join(", ")}`);
}
export function benchStrings(value, path) { const values = benchArray(value, path); values.forEach((item, index) => benchText(item, `${path}[${index}]`)); return values; }
export function benchUnique(values, path) { requireBench(values.length === new Set(values).size, `${path} contains duplicate identifiers`); return new Set(values); }
function exactSet(values, expected) { return values.size === expected.size && [...values].every((item) => expected.has(item)); }
function validateHeader(value, type, path) { const artifact = benchRecord(value, path); requireBench(artifact.artifact_type === type, `${path}.artifact_type must be ${type}`); requireBench(artifact.schema_version === 1, `${path}.schema_version must be 1`); return artifact; }
function validateSnapshot(value, path) {
  const snapshot = benchRecord(value, path); benchExact(snapshot, ["kind", "identity", "digest", "reconstruction_confidence", "limitations"], ["repository", "tree_oid"], path);
  requireBench(SETS.snapshotKind.has(snapshot.kind), `${path}.kind is invalid`); benchText(snapshot.identity, `${path}.identity`);
  requireBench(/^[0-9a-f]{64}$/.test(benchText(snapshot.digest, `${path}.digest`)), `${path}.digest must be lowercase sha256`);
  requireBench(SETS.reconstruction.has(snapshot.reconstruction_confidence), `${path}.reconstruction_confidence is invalid`); benchStrings(snapshot.limitations, `${path}.limitations`);
  if ("repository" in snapshot) benchText(snapshot.repository, `${path}.repository`); if ("tree_oid" in snapshot) benchText(snapshot.tree_oid, `${path}.tree_oid`);
}
function validateCase(value, path) {
  const item = benchRecord(value, path); benchExact(item, ["case_id", "title", "review_class", "risk", "change_profile", "contract", "snapshot", "artifacts", "deterministic_evidence", "limitations"], [], path);
  benchText(item.case_id, `${path}.case_id`); benchText(item.title, `${path}.title`); requireBench(SETS.reviewClass.has(item.review_class), `${path}.review_class is invalid`); requireBench(SETS.risk.has(item.risk), `${path}.risk is invalid`);
  const profile = benchRecord(item.change_profile, `${path}.change_profile`); benchExact(profile, ["route_class", "semantic_domains", "topologies", "novelty", "evidence_types", "consequences"], ["changed_files", "changed_lines"], `${path}.change_profile`);
  requireBench(SETS.routeClass.has(profile.route_class), `${path}.change_profile.route_class is invalid`);
  for (const [key, vocabulary] of [["semantic_domains", SETS.domain], ["topologies", SETS.topology], ["evidence_types", SETS.evidence], ["consequences", SETS.consequence]]) { const values = benchStrings(profile[key], `${path}.change_profile.${key}`); requireBench(values.length > 0, `${path}.change_profile.${key} must not be empty`); requireBench(values.every((x) => vocabulary.has(x)), `${path}.change_profile.${key} contains invalid values`); benchUnique(values, `${path}.change_profile.${key}`); }
  requireBench(SETS.novelty.has(profile.novelty), `${path}.change_profile.novelty is invalid`); for (const key of ["changed_files", "changed_lines"]) if (key in profile) benchNumber(profile[key], `${path}.change_profile.${key}`);
  const contract = benchRecord(item.contract, `${path}.contract`); benchExact(contract, ["goal", "acceptance_criteria", "excluded_scope"], [], `${path}.contract`); benchText(contract.goal, `${path}.contract.goal`); requireBench(benchStrings(contract.acceptance_criteria, `${path}.contract.acceptance_criteria`).length > 0, `${path}.contract.acceptance_criteria must not be empty`); benchStrings(contract.excluded_scope, `${path}.contract.excluded_scope`);
  validateSnapshot(item.snapshot, `${path}.snapshot`); benchArray(item.artifacts, `${path}.artifacts`).forEach((artifact, index) => { const p = `${path}.artifacts[${index}]`; benchExact(artifact, ["path", "role"], ["sha256"], p); benchText(artifact.path, `${p}.path`); benchText(artifact.role, `${p}.role`); if ("sha256" in artifact) requireBench(benchText(artifact.sha256, `${p}.sha256`).length === 64, `${p}.sha256 must be 64 characters`); });
  benchStrings(item.deterministic_evidence, `${path}.deterministic_evidence`); benchStrings(item.limitations, `${path}.limitations`);
}
export function validateReviewBenchCorpus(value) {
  const corpus = validateHeader(value, "review_bench_corpus_v1", "corpus"); benchExact(corpus, ["artifact_type", "schema_version", "bench_id", "protocol", "cases"], [], "corpus"); benchText(corpus.bench_id, "corpus.bench_id");
  const protocol = benchRecord(corpus.protocol, "corpus.protocol"); benchExact(protocol, ["name", "version", "prompt", "verdicts", "severities", "confidence_scale"], [], "corpus.protocol"); ["name", "version", "prompt"].forEach((key) => benchText(protocol[key], `corpus.protocol.${key}`));
  requireBench(exactSet(new Set(benchStrings(protocol.verdicts, "corpus.protocol.verdicts")), SETS.verdict), "corpus.protocol.verdicts must use the complete vocabulary"); requireBench(exactSet(new Set(benchStrings(protocol.severities, "corpus.protocol.severities")), SETS.severity), "corpus.protocol.severities must use the complete vocabulary"); requireBench(exactSet(new Set(benchStrings(protocol.confidence_scale, "corpus.protocol.confidence_scale")), SETS.confidence), "corpus.protocol.confidence_scale must use the complete vocabulary");
  const cases = benchArray(corpus.cases, "corpus.cases"); requireBench(cases.length > 0, "corpus.cases must not be empty"); cases.forEach((item, index) => validateCase(item, `corpus.cases[${index}]`)); benchUnique(cases.map((item) => item.case_id), "corpus.cases"); return corpus;
}
function validateTruthCases(truth, corpus) {
  requireBench(truth.bench_id === corpus.bench_id, "truth.bench_id does not match corpus"); const corpusIds = new Set(corpus.cases.map((item) => item.case_id)); const cases = benchArray(truth.cases, "truth.cases"); requireBench(exactSet(new Set(cases.map((item) => item.case_id)), corpusIds), "truth.cases must exactly cover corpus cases");
  cases.forEach((item, index) => { const p = `truth.cases[${index}]`; benchExact(item, ["case_id", "expected_verdict", "findings", "adjudication_notes"], [], p); benchText(item.case_id, `${p}.case_id`); requireBench(SETS.verdict.has(item.expected_verdict), `${p}.expected_verdict is invalid`); const ids=[]; benchArray(item.findings, `${p}.findings`).forEach((finding, n) => { const f=`${p}.findings[${n}]`; benchExact(finding, ["truth_id", "severity", "blocking", "category", "claim", "evidence", "adjudication", "tags"], [], f); ids.push(benchText(finding.truth_id, `${f}.truth_id`)); requireBench(SETS.severity.has(finding.severity), `${f}.severity is invalid`); benchBoolean(finding.blocking, `${f}.blocking`); benchText(finding.category, `${f}.category`); benchText(finding.claim, `${f}.claim`); requireBench(benchStrings(finding.evidence, `${f}.evidence`).length > 0, `${f}.evidence must not be empty`); benchText(finding.adjudication, `${f}.adjudication`); benchStrings(finding.tags, `${f}.tags`); }); benchUnique(ids, `${p}.findings`); benchStrings(item.adjudication_notes, `${p}.adjudication_notes`); }); benchStrings(truth.limitations, "truth.limitations");
}
function truthTarget(truth, caseId, findingId, field, path) { const item=truth.cases.find((x)=>x.case_id===caseId); requireBench(item, `${path}.case_id is unknown`); if (field === "expected_verdict") { requireBench(findingId === null, `${path}.finding_id must be null for expected_verdict`); return item[field]; } requireBench(["finding.blocking","finding.severity","finding.adjudication"].includes(field), `${path}.field is invalid`); benchText(findingId, `${path}.finding_id`); const finding=item.findings.find((x)=>x.truth_id===findingId); requireBench(finding, `${path}.finding_id is unknown`); return finding[field.split(".")[1]]; }
export function validateReviewBenchTruth(value, corpus, { supersededTruth = null, supersededSha256 = null } = {}) {
  const truth=benchRecord(value,"truth"); requireBench([1,2].includes(truth.schema_version), "truth.schema_version must be 1 or 2"); requireBench(truth.artifact_type===`review_bench_truth_v${truth.schema_version}`, `truth.artifact_type must be review_bench_truth_v${truth.schema_version}`);
  if (truth.schema_version===1) { benchExact(truth,["artifact_type","schema_version","bench_id","cases","limitations"],[],"truth"); validateTruthCases(truth,corpus); return truth; }
  benchExact(truth,["artifact_type","schema_version","bench_id","supersedes","adjudication_amendments","cases","limitations"],[],"truth"); validateTruthCases(truth,corpus); benchExact(truth.supersedes,["artifact_type","path","sha256"],[],"truth.supersedes"); requireBench(truth.supersedes.artifact_type==="review_bench_truth_v1","truth.supersedes.artifact_type must be review_bench_truth_v1"); const rel=benchText(truth.supersedes.path,"truth.supersedes.path"); requireBench(!rel.startsWith("/")&&!rel.split(/[\\/]/).includes(".."),"truth.supersedes.path must be a contained relative path"); requireBench(/^[0-9a-f]{64}$/.test(truth.supersedes.sha256),"truth.supersedes.sha256 must be lowercase sha256"); if(supersededSha256!==null) requireBench(supersededSha256===truth.supersedes.sha256,"truth superseded artifact sha256 does not match"); if(supersededTruth) validateReviewBenchTruth(supersededTruth,corpus);
  const ids=[], targets=new Set(); const amendments=benchArray(truth.adjudication_amendments,"truth.adjudication_amendments"); requireBench(amendments.length>0,"truth.adjudication_amendments must not be empty"); amendments.forEach((amendment,index)=>{const p=`truth.adjudication_amendments[${index}]`; benchExact(amendment,["amendment_id","adjudicated_at","adjudicator","reason","evidence","changes","limitations"],[],p); ids.push(benchText(amendment.amendment_id,`${p}.amendment_id`)); ["adjudicated_at","adjudicator","reason"].forEach((key)=>benchText(amendment[key],`${p}.${key}`)); requireBench(benchStrings(amendment.evidence,`${p}.evidence`).length>0,`${p}.evidence must not be empty`); benchStrings(amendment.limitations,`${p}.limitations`); const changes=benchArray(amendment.changes,`${p}.changes`); requireBench(changes.length>0,`${p}.changes must not be empty`); changes.forEach((change,n)=>{const c=`${p}.changes[${n}]`; benchExact(change,["case_id","finding_id","field","before","after"],[],c); benchText(change.case_id,`${c}.case_id`); requireBench(change.finding_id===null||typeof change.finding_id==="string",`${c}.finding_id must be string or null`); benchText(change.field,`${c}.field`); const target=JSON.stringify([change.case_id,change.finding_id,change.field]); requireBench(!targets.has(target),`${c} duplicates an amended target`); targets.add(target); if(supersededTruth){requireBench(truthTarget(supersededTruth,change.case_id,change.finding_id,change.field,c)===change.before,`${c}.before does not match superseded truth`); requireBench(truthTarget(truth,change.case_id,change.finding_id,change.field,c)===change.after,`${c}.after does not match amended truth`);} requireBench(change.before!==change.after,`${c} must change the value`);});}); benchUnique(ids,"truth.adjudication_amendments"); return truth;
}
export function validateReviewBenchResult(value, corpus) {
  const result=benchRecord(value,"result"); requireBench([1,2].includes(result.schema_version),"result.schema_version must be 1 or 2"); requireBench(result.artifact_type===`review_bench_result_v${result.schema_version}`,`result.artifact_type must be review_bench_result_v${result.schema_version}`); const extra=result.schema_version===2?["verified_claims","observations"]:[]; benchExact(result,["artifact_type","schema_version","bench_id","case_id","result_id","attempt_id","reviewer","snapshot_digest","verdict","findings","limitations","timing",...extra],[],"result"); requireBench(result.bench_id===corpus.bench_id,"result.bench_id does not match corpus"); const item=corpus.cases.find((x)=>x.case_id===result.case_id); requireBench(item,"result.case_id is not in corpus"); benchText(result.result_id,"result.result_id"); benchText(result.attempt_id,"result.attempt_id"); const reviewer=benchRecord(result.reviewer,"result.reviewer"); benchExact(reviewer,["provider","model","harness","inference_family","fresh_context","tool_access","reasoning_effort","review_protocol","pass_count","aggregation_strategy","aggregation_members"],["session_id"],"result.reviewer"); ["provider","model","harness","inference_family"].forEach((key)=>benchText(reviewer[key],`result.reviewer.${key}`)); benchBoolean(reviewer.fresh_context,"result.reviewer.fresh_context"); benchStrings(reviewer.tool_access,"result.reviewer.tool_access"); if("session_id" in reviewer)benchText(reviewer.session_id,"result.reviewer.session_id"); requireBench(SETS.reasoning.has(reviewer.reasoning_effort),"result.reviewer.reasoning_effort is invalid"); benchText(reviewer.review_protocol,"result.reviewer.review_protocol"); benchInteger(reviewer.pass_count,"result.reviewer.pass_count"); requireBench(SETS.aggregation.has(reviewer.aggregation_strategy),"result.reviewer.aggregation_strategy is invalid"); const members=benchStrings(reviewer.aggregation_members,"result.reviewer.aggregation_members"); benchUnique(members,"result.reviewer.aggregation_members"); if(reviewer.pass_count===1)requireBench(reviewer.aggregation_strategy==="none","result.reviewer.aggregation_strategy must be none for one pass"); if(reviewer.aggregation_strategy==="none")requireBench(!members.length,"result.reviewer.aggregation_members must be empty without aggregation"); else {requireBench(reviewer.pass_count>1,"aggregated results require more than one pass");requireBench(members.length,"aggregated results require aggregation_members");} if(reviewer.aggregation_strategy==="self_aggregation")requireBench(members.length===1,"self_aggregation requires exactly one member configuration"); if(reviewer.aggregation_strategy==="cross_model_aggregation")requireBench(members.length>=2,"cross_model_aggregation requires at least two member configurations"); requireBench(result.snapshot_digest===item.snapshot.digest,"result.snapshot_digest does not match the case"); requireBench(SETS.verdict.has(result.verdict),"result.verdict is invalid");
  const findingIds=[]; benchArray(result.findings,"result.findings").forEach((finding,index)=>{const p=`result.findings[${index}]`; benchExact(finding,["finding_id","severity","blocking","category","claim","evidence","confidence"],[],p); findingIds.push(benchText(finding.finding_id,`${p}.finding_id`)); requireBench(SETS.severity.has(finding.severity),`${p}.severity is invalid`); benchBoolean(finding.blocking,`${p}.blocking`); benchText(finding.category,`${p}.category`); benchText(finding.claim,`${p}.claim`); requireBench(benchStrings(finding.evidence,`${p}.evidence`).length>0,`${p}.evidence must not be empty`); requireBench(SETS.confidence.has(finding.confidence),`${p}.confidence is invalid`);}); benchUnique(findingIds,"result.findings");
  if(result.schema_version===2){const criteria=new Set(item.contract.acceptance_criteria), verifiedIds=[], covered=new Set(); benchArray(result.verified_claims,"result.verified_claims").forEach((claim,index)=>{const p=`result.verified_claims[${index}]`;benchExact(claim,["claim_id","claim","evidence","confidence","acceptance_criteria"],[],p);verifiedIds.push(benchText(claim.claim_id,`${p}.claim_id`));benchText(claim.claim,`${p}.claim`);requireBench(benchStrings(claim.evidence,`${p}.evidence`).length>0,`${p}.evidence must not be empty`);requireBench(claim.confidence==="high",`${p}.confidence must be high`);const values=benchStrings(claim.acceptance_criteria,`${p}.acceptance_criteria`);requireBench(values.length,`${p}.acceptance_criteria must not be empty`);requireBench(values.every((x)=>criteria.has(x)),`${p}.acceptance_criteria must quote criteria from the case contract`);values.forEach((x)=>covered.add(x));});benchUnique(verifiedIds,"result.verified_claims");const observationIds=[];benchArray(result.observations,"result.observations").forEach((observation,index)=>{const p=`result.observations[${index}]`;benchExact(observation,["observation_id","category","claim","evidence","confidence"],[],p);observationIds.push(benchText(observation.observation_id,`${p}.observation_id`));benchText(observation.category,`${p}.category`);benchText(observation.claim,`${p}.claim`);requireBench(benchStrings(observation.evidence,`${p}.evidence`).length>0,`${p}.evidence must not be empty`);requireBench(SETS.confidence.has(observation.confidence),`${p}.confidence is invalid`);});benchUnique(observationIds,"result.observations");benchUnique([...findingIds,...verifiedIds,...observationIds],"result item identifiers");if(result.verdict==="accepted"){requireBench(!result.findings.some((x)=>x.blocking),"accepted result v2 cannot contain a blocking finding");requireBench(exactSet(covered,criteria),"accepted result v2 must verify every case acceptance criterion");}if(result.verdict==="rejected")requireBench(result.findings.some((x)=>x.blocking),"rejected result v2 requires a blocking finding");}
  benchStrings(result.limitations,"result.limitations"); benchExact(result.timing,["started_at","completed_at"],["wall_clock_seconds","cost_usd","input_tokens","output_tokens"],"result.timing"); benchText(result.timing.started_at,"result.timing.started_at"); benchText(result.timing.completed_at,"result.timing.completed_at"); ["wall_clock_seconds","cost_usd","input_tokens","output_tokens"].forEach((key)=>{if(key in result.timing)benchNumber(result.timing[key],`result.timing.${key}`);}); return result;
}
export function validateReviewBenchScoring(value, corpus, truth, result) {
  const scoring=validateHeader(value,"review_bench_scoring_v1","scoring");benchExact(scoring,["artifact_type","schema_version","bench_id","case_id","result_id","finding_dispositions","missed_truth_ids","adjudicator","limitations"],[],"scoring");requireBench(scoring.bench_id===corpus.bench_id,"scoring.bench_id does not match corpus");requireBench(scoring.case_id===result.case_id,"scoring.case_id does not match result");requireBench(scoring.result_id===result.result_id,"scoring.result_id does not match result");const truthCase=truth.cases.find((x)=>x.case_id===result.case_id), truthIds=new Set(truthCase.findings.map((x)=>x.truth_id)), resultIds=new Set(result.findings.map((x)=>x.finding_id)), observed=[], detected=new Set(); benchArray(scoring.finding_dispositions,"scoring.finding_dispositions").forEach((entry,index)=>{const p=`scoring.finding_dispositions[${index}]`;benchExact(entry,["result_finding_id","disposition","truth_finding_ids","evidence_valid","notes"],[],p);const id=benchText(entry.result_finding_id,`${p}.result_finding_id`);observed.push(id);requireBench(resultIds.has(id),`${p}.result_finding_id is unknown`);requireBench(SETS.disposition.has(entry.disposition),`${p}.disposition is invalid`);const mapped=new Set(benchStrings(entry.truth_finding_ids,`${p}.truth_finding_ids`));requireBench([...mapped].every((x)=>truthIds.has(x)),`${p}.truth_finding_ids contains unknown truth`);if(entry.disposition==="true_positive"){requireBench(mapped.size,`${p}.true_positive requires truth_finding_ids`);mapped.forEach((x)=>detected.add(x));}else requireBench(!mapped.size||entry.disposition==="duplicate",`${p}.truth_finding_ids are only valid for true_positive or duplicate`);benchBoolean(entry.evidence_valid,`${p}.evidence_valid`);benchText(entry.notes,`${p}.notes`);});requireBench(new Set(observed).size===resultIds.size&&observed.length===resultIds.size&&observed.every((x)=>resultIds.has(x)),"scoring dispositions must classify every result finding exactly once");const missed=new Set(benchStrings(scoring.missed_truth_ids,"scoring.missed_truth_ids")), expected=new Set([...truthIds].filter((x)=>!detected.has(x)));requireBench(exactSet(missed,expected),"scoring.missed_truth_ids must exactly equal undetected truth findings");benchText(scoring.adjudicator,"scoring.adjudicator");benchStrings(scoring.limitations,"scoring.limitations");return scoring;
}
