import {
  benchArray, benchRecord, requireBench, validateReviewBenchCorpus, validateReviewBenchResult,
  validateReviewBenchScoring, validateReviewBenchTruth,
} from "./contract.mjs";
import { compareReviewBenchResults } from "./comparison.mjs";

export function renderReviewBenchPrompt(corpus, item) {
  const protocol=corpus.protocol, contract=item.contract;
  const lines=[`# Review case: ${item.title}`,"",protocol.prompt.trim(),"","## Exact case identity","",`- Bench: \`${corpus.bench_id}\``,`- Case: \`${item.case_id}\``,`- Snapshot: \`${item.snapshot.identity}\``,`- Snapshot digest: \`${item.snapshot.digest}\``,`- Review class: \`${item.review_class}\``,`- Route class: \`${item.change_profile.route_class}\``,`- Semantic domains: \`${item.change_profile.semantic_domains.join(", ")}\``,`- Topologies: \`${item.change_profile.topologies.join(", ")}\``,`- Novelty: \`${item.change_profile.novelty}\``,`- Evidence types: \`${item.change_profile.evidence_types.join(", ")}\``,`- Consequences: \`${item.change_profile.consequences.join(", ")}\``,`- Risk: \`${item.risk}\``,"","## Contract","",contract.goal,"","Acceptance criteria:","",...contract.acceptance_criteria.map((x)=>`- ${x}`),"","Excluded scope:","",...contract.excluded_scope.map((x)=>`- ${x}`),"","## Available artifacts","",...item.artifacts.map((x)=>`- \`${x.path}\` — ${x.role}`),"","## Deterministic evidence","",...item.deterministic_evidence.map((x)=>`- ${x}`)];
  if(protocol.version==="1.2")lines.push("","Return one `review_bench_result_v2` JSON object with `findings`, `verified_claims`, and `observations` arrays. Do not include ground-truth identifiers.","Put only claimed defects or material risks in `findings`; each may carry severity and blocking status.","Put acceptance-critical conclusions established by evidence in `verified_claims`; identify the supported acceptance criteria and do not attach severity or blocking status.","Put real non-defect improvements or out-of-contract notes in `observations`; do not attach severity or blocking status.","Finding fields are `finding_id`, `severity`, `blocking`, `category`, `claim`, `evidence`, and `confidence`.","Verified-claim fields are `claim_id`, `claim`, `evidence`, `confidence`, and `acceptance_criteria`; quote supported criteria verbatim from this case.","Observation fields are `observation_id`, `category`, `claim`, `evidence`, and `confidence`.","Verified claims require high confidence. An accepted verdict must verify every listed acceptance criterion and contain no blocking finding; otherwise use the evidence-supported non-acceptance verdict.","Do not duplicate one claim across arrays. Use only the configured verdict, severity, and confidence vocabularies.","Every item must cite concrete evidence from the supplied snapshot.","");
  else lines.push("","Return one `review_bench_result_v1` JSON object. Do not include ground-truth identifiers.","Use only the configured verdict, severity, and confidence vocabularies.","Every finding must cite concrete evidence from the supplied snapshot.","");
  return lines.join("\n");
}

export function renderReviewBenchCase(corpusValue, caseId) {
  const corpus=validateReviewBenchCorpus(corpusValue), item=corpus.cases.find((x)=>x.case_id===caseId); requireBench(item,`case '${caseId}' is not in corpus`);
  return Object.freeze({packet:{artifact_type:"review_bench_case_packet_v1",schema_version:1,bench_id:corpus.bench_id,protocol:structuredClone(corpus.protocol),case:structuredClone(item)},prompt:renderReviewBenchPrompt(corpus,item),archive_required:false});
}

function summarizeFindings(value){if(!value||Array.isArray(value)||typeof value!=="object")return false;return Object.values(value).some((nested)=>typeof nested==="boolean"?false:(typeof nested==="number"&&nested>0)||(nested&&typeof nested==="object"&&summarizeFindings(nested)));}
export function inventoryReviewBenchHistory(rowsValue, sessionCandidatesValue={}) {
  const rows=benchArray(rowsValue,"inventory.rows"), sessions=benchRecord(sessionCandidatesValue,"inventory.session_candidates"), candidates=[];
  for(const row of rows){benchRecord(row,"inventory row");const worker=row.worker_metrics&&typeof row.worker_metrics==="object"&&!Array.isArray(row.worker_metrics)?row.worker_metrics:{};const reviewCalls=worker.review_gate_calls??0,fixIterations=worker.review_fix_iterations??row.review_fix_iterations??0,findings=row.review_findings,ownedFiles=row.task_owned_files??worker.task_owned_files??[],additional=worker.additional_metrics&&typeof worker.additional_metrics==="object"?worker.additional_metrics:{},workspace=additional.workspace&&typeof additional.workspace==="object"?additional.workspace:{},snapshotHead=workspace.head??null,records=Array.isArray(sessions[String(row.run_id)])?sessions[String(row.run_id)]:[],pattern=new RegExp(`(?:^|_)slice${String(row.slice_number).replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}(?:_|$)`),exact=records.filter((item)=>item&&item.agent_path&&pattern.test(item.agent_path)).map((item)=>item.path),runSessions=exact.length?exact:records.map((item)=>item.path),quality=exact.length?"run_and_slice":runSessions.length?"run_only":"none";if(!(reviewCalls||fixIterations||summarizeFindings(findings)))continue;let reconstruction,missing;if(snapshotHead&&ownedFiles.length){reconstruction="partial";missing=["immutable dirty-worktree tree or checkpoint"];}else if(runSessions.length&&ownedFiles.length){reconstruction="forensic_only";missing=["immutable snapshot identity","verified patch reconstruction"];}else{reconstruction="insufficient";missing=["immutable snapshot identity","complete task-owned manifest"];}candidates.push({run_id:row.run_id??null,slice_number:row.slice_number??null,slice_title:row.slice_title??null,status:row.status??null,review_gate_calls:reviewCalls||0,review_fix_iterations:fixIterations||0,has_finding_summary:findings!==undefined,has_nonzero_findings:summarizeFindings(findings),task_owned_files:ownedFiles,snapshot_head:snapshotHead,codex_session_candidates:runSessions,session_match_quality:quality,reconstruction_state:reconstruction,missing_for_exact_case:missing});}
  const counts={};for(const candidate of candidates)counts[candidate.reconstruction_state]=(counts[candidate.reconstruction_state]??0)+1;
  return {artifact_type:"review_bench_inventory_v1",schema_version:1,status:"provisional_inventory",source_receipts:rows.length,candidate_cases:candidates.length,reconstruction_states:Object.fromEntries(Object.entries(counts).sort(([a],[b])=>a.localeCompare(b))),candidates,limitations:["Provider attempt counts may combine placement and implementation-review activity in historical receipts.","A Git HEAD does not identify uncommitted reviewed content.","Session matches are candidates and require prompt/result extraction before use."]};
}

export class ExperimentalReviewBenchService {
  validate({corpus:corpusValue,truth:truthValue=null,result:resultValue=null,scoring:scoringValue=null,supersededTruth=null,supersededSha256=null}={}){const corpus=validateReviewBenchCorpus(corpusValue),truth=truthValue?validateReviewBenchTruth(truthValue,corpus,{supersededTruth,supersededSha256}):null,result=resultValue?validateReviewBenchResult(resultValue,corpus):null;if(scoringValue){requireBench(truth&&result,"scoring requires truth and result");validateReviewBenchScoring(scoringValue,corpus,truth,result);}return Object.freeze({status:"valid",bench_id:corpus.bench_id,experimental:true,production_review_authority:false});}
  compare({corpus:corpusValue,truth:truthValue,results:resultValues,scorings:scoringValues}={}){const corpus=validateReviewBenchCorpus(corpusValue),truth=validateReviewBenchTruth(truthValue,corpus),results=benchArray(resultValues,"results").map((value)=>validateReviewBenchResult(value,corpus)),byId=new Map(results.map((value)=>[value.result_id,value]));requireBench(byId.size===results.length,"results contains duplicate identifiers");const scorings=benchArray(scoringValues,"scorings").map((value)=>{const result=byId.get(value.result_id);requireBench(result,"scoring names unknown result_id");return validateReviewBenchScoring(value,corpus,truth,result);});return compareReviewBenchResults(corpus,truth,results,scorings);}
  renderCase({corpus,caseId}={}){return renderReviewBenchCase(corpus,caseId);}
  inventory({rows,sessionCandidates={}}={}){return inventoryReviewBenchHistory(rows,sessionCandidates);}
}
