#!/usr/bin/env python3
"""Validate, analyze, and render Work Engine Agent Environment Graph inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml


class GraphError(ValueError):
    """Raised when graph inputs or judgments violate their deterministic contract."""


SEMANTIC_CATEGORIES = {
    "invariant_status", "causal_parent", "ownership", "authority",
    "conditionality", "equivalence",
}
TOP_LEVEL_KEYS = {
    "schema_version", "document_id", "status", "verified_on", "scope",
    "sources", "semantics", "entities", "roles", "analysis_queries",
}
ROLE_KEYS = {
    "label", "objective", "context_lifetime", "bound_by", "must_require",
    "may_invoke", "may_observe", "observation_limits", "may_mutate", "owns",
    "consumes", "emits", "mediated_transitions", "forbidden_from", "independence",
}
RELATION_LISTS = ("bound_by", "may_invoke", "may_observe", "owns", "consumes", "emits")
RELATION_LABELS = {
    "bound_by": "BOUND_BY", "may_invoke": "MAY_INVOKE", "owns": "OWNS",
    "may_observe": "MAY_OBSERVE", "consumes": "CONSUMES", "emits": "EMITS",
}
MERMAID_CLASS_DEFS = (
    "  classDef role fill:#111827,color:#ffffff,stroke:#000000,stroke-width:3px",
    "  classDef invAuthority fill:#fef3c7,color:#451a03,stroke:#eab308,stroke-width:2px",
    "  classDef invOwnership fill:#ede9fe,color:#2e1065,stroke:#7c3aed,stroke-width:2px",
    "  classDef invMutation fill:#fee2e2,color:#450a0a,stroke:#dc2626,stroke-width:2px",
    "  classDef invAcceptance fill:#dcfce7,color:#052e16,stroke:#16a34a,stroke-width:2px",
    "  classDef invTruth fill:#92400e,color:#ffffff,stroke:#78350f,stroke-width:2px",
    "  classDef invInterface fill:#dbeafe,color:#172554,stroke:#2563eb,stroke-width:2px",
    "  classDef invIndependence fill:#ede9fe,color:#2e1065,stroke:#7c3aed,stroke-width:2px",
    "  classDef invSecurity fill:#fee2e2,color:#450a0a,stroke:#dc2626,stroke-width:2px",
    "  classDef invLifecycle fill:#ffffff,color:#111827,stroke:#9ca3af,stroke-width:2px",
    "  classDef invDefault fill:#111827,color:#ffffff,stroke:#000000,stroke-width:2px",
    "  classDef capability fill:#dbeafe,color:#172554,stroke:#2563eb,stroke-width:2px",
    "  classDef owned fill:#dcfce7,color:#052e16,stroke:#16a34a,stroke-width:2px",
    "  classDef observable fill:#dbeafe,color:#172554,stroke:#2563eb,stroke-width:2px",
    "  classDef forbidden fill:#fee2e2,color:#450a0a,stroke:#dc2626,stroke-width:2px",
    "  classDef transition fill:#ffedd5,color:#431407,stroke:#ea580c,stroke-width:2px",
)
STYLE_SEMANTICS = {
    "role": ("⚫", "role"),
    "invAuthority": ("🟡", "authority"),
    "invOwnership": ("🟣", "ownership"),
    "invMutation": ("🔴", "mutation"),
    "invAcceptance": ("🟢", "acceptance"),
    "invTruth": ("🟤", "truth/provenance"),
    "invInterface": ("🔵", "interface"),
    "invIndependence": ("🟣", "independence"),
    "invSecurity": ("🔴", "security"),
    "invLifecycle": ("⚪", "lifecycle/context"),
    "invDefault": ("⚫", "unclassified"),
    "capability": ("🔵", "capability"),
    "owned": ("🟢", "owned/output"),
    "observable": ("🔵", "observation/input"),
    "forbidden": ("🔴", "prohibition"),
    "transition": ("🟠", "mediated transition"),
}
GENERATED_COMMENT = "<!-- Generated by skills/agent-environment-graph/scripts/agent_environment_graph.py. -->"
GENERATED_YAML_COMMENT = "# Generated by skills/agent-environment-graph/scripts/agent_environment_graph.py."


class UniqueKeyLoader(yaml.SafeLoader):
    pass


def _construct_mapping(loader: UniqueKeyLoader, node: yaml.MappingNode, deep: bool = False) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        if key in result:
            raise GraphError(f"duplicate YAML key: {key}")
        result[key] = loader.construct_object(value_node, deep=deep)
    return result


UniqueKeyLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _construct_mapping)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise GraphError(message)


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        value = yaml.load(path.read_text(encoding="utf-8"), Loader=UniqueKeyLoader)
    except yaml.YAMLError as error:
        raise GraphError(f"invalid YAML: {error}") from error
    require(isinstance(value, dict), "environment document must be a mapping")
    return value


def _split_row(line: str) -> list[str]:
    """Split a Markdown table row while preserving escaped pipes as cell text."""
    value = line.strip()
    if value.startswith("|"):
        value = value[1:]
    if value.endswith("|") and not value.endswith(r"\|"):
        value = value[:-1]
    cells: list[str] = []
    cell: list[str] = []
    index = 0
    while index < len(value):
        character = value[index]
        if character == "\\" and index + 1 < len(value) and value[index + 1] == "|":
            cell.append("|")
            index += 2
            continue
        if character == "|":
            cells.append("".join(cell).strip())
            cell = []
        else:
            cell.append(character)
        index += 1
    cells.append("".join(cell).strip())
    return cells


def _table_rows(source: str, heading: str) -> list[list[str]]:
    start = source.find(heading)
    require(start >= 0, f"missing section: {heading}")
    tail = source[start + len(heading):]
    boundary = re.search(r"\n##(?:#)? ", tail)
    section = tail[:boundary.start()] if boundary else tail
    rows = []
    for line in section.splitlines():
        if not line.startswith("|") or re.match(r"^\|[ -]+\|", line):
            continue
        cells = _split_row(line)
        if cells and cells[0] not in {"ID", "Field"}:
            rows.append(cells)
    return rows


def parse_invariants(path: Path) -> dict[str, Any]:
    source = path.read_text(encoding="utf-8")
    invariant_rows: list[list[str]] = []
    catalog_start = source.find("## Invariant catalog")
    machinery_start = source.find("## Current machinery catalog")
    require(catalog_start >= 0 and machinery_start > catalog_start, "missing invariant or machinery catalog")
    for line in source[catalog_start:machinery_start].splitlines():
        if line.startswith("|"):
            cells = _split_row(line)
            if cells and re.fullmatch(r"`INV-[0-9]+`", cells[0]):
                invariant_rows.append(cells)
    mechanism_rows = _table_rows(source, "## Current machinery catalog")
    invariants: dict[str, dict[str, Any]] = {}
    for row in invariant_rows:
        require(len(row) == 10, f"malformed invariant row: {row[0]}")
        identifier = row[0].strip("`")
        require(identifier not in invariants, f"duplicate invariant id: {identifier}")
        invariants[identifier] = {
            "owner": row[1], "applies": row[2], "class": row[3],
            "condition": row[4], "causal_parent": row[5], "enforcement": row[6],
            "mechanisms": re.findall(r"`(MECH-[A-Z0-9-]+)`", row[7]),
            "relations": re.findall(r"`(INV-[0-9]+)`", row[8]), "sources": row[9],
        }
    mechanisms: dict[str, dict[str, str]] = {}
    for row in mechanism_rows:
        if not row or not re.fullmatch(r"`MECH-[A-Z0-9-]+`", row[0]):
            continue
        require(len(row) == 4, f"malformed mechanism row: {row[0]}")
        identifier = row[0].strip("`")
        require(identifier not in mechanisms, f"duplicate mechanism id: {identifier}")
        mechanisms[identifier] = {"component": row[1], "affordance": row[2], "edges": row[3]}
    require(bool(invariants), "invariant catalog is empty")
    require(bool(mechanisms), "machinery catalog is empty")
    for identifier, item in invariants.items():
        for target in item["relations"]:
            require(target in invariants, f"{identifier} references unknown invariant {target}")
        for mechanism in item["mechanisms"]:
            require(mechanism in mechanisms, f"{identifier} references unknown mechanism {mechanism}")
    return {"invariants": invariants, "mechanisms": mechanisms, "source": source}


def _unique_strings(values: Any, path: str) -> list[str]:
    require(isinstance(values, list), f"{path} must be a list")
    require(all(isinstance(value, str) and value for value in values), f"{path} must contain nonempty strings")
    require(len(values) == len(set(values)), f"{path} contains duplicate values")
    return values


def validate_environment(data: dict[str, Any], catalog: dict[str, Any]) -> dict[str, Any]:
    unknown = set(data) - TOP_LEVEL_KEYS
    require(not unknown, f"unknown environment fields: {', '.join(sorted(unknown))}")
    require(data.get("schema_version") == 1, "schema_version must be 1")
    entities = data.get("entities")
    roles = data.get("roles")
    require(isinstance(entities, dict) and isinstance(roles, dict) and roles, "entities and roles are required mappings")
    require(set(entities) == {"states", "artifacts", "capabilities"}, "entities must contain states, artifacts, capabilities")
    entity_ids: set[str] = set()
    for kind, mapping in entities.items():
        require(isinstance(mapping, dict), f"entities.{kind} must be a mapping")
        for identifier, item in mapping.items():
            require(identifier not in entity_ids, f"duplicate entity id: {identifier}")
            require(isinstance(item, dict) and isinstance(item.get("label"), str), f"{identifier} requires a label")
            allowed = {"label", "mechanism", "configured", "configured_or_risk_selected"}
            require(not set(item) - allowed, f"{identifier} has unknown fields")
            if "mechanism" in item:
                require(item["mechanism"] in catalog["mechanisms"], f"{identifier} references unknown mechanism {item['mechanism']}")
            entity_ids.add(identifier)
    role_ids = set(roles)
    for role_id, role in roles.items():
        require(role_id.startswith("role.") and isinstance(role, dict), f"invalid role: {role_id}")
        require(not set(role) - ROLE_KEYS, f"{role_id} has unknown fields: {', '.join(sorted(set(role) - ROLE_KEYS))}")
        for required in ("label", "objective", "context_lifetime"):
            require(isinstance(role.get(required), str) and role[required].strip(), f"{role_id}.{required} is required")
        for field in RELATION_LISTS:
            for target in _unique_strings(role.get(field, []), f"{role_id}.{field}"):
                if field == "bound_by":
                    require(target in catalog["invariants"], f"{role_id}.{field} references unknown invariant {target}")
                else:
                    require(target in entity_ids, f"{role_id}.{field} references unknown entity {target}")
        for target_role, invariant_ids in role.get("must_require", {}).items():
            require(target_role in role_ids, f"{role_id}.must_require references unknown role {target_role}")
            for invariant_id in _unique_strings(invariant_ids, f"{role_id}.must_require.{target_role}"):
                require(invariant_id in catalog["invariants"], f"{role_id}.must_require references unknown invariant {invariant_id}")
        for index, mutation in enumerate(role.get("may_mutate", [])):
            require(isinstance(mutation, dict) and set(mutation) == {"target", "boundary"}, f"{role_id}.may_mutate[{index}] has invalid shape")
            require(mutation["target"] in entity_ids and isinstance(mutation["boundary"], str), f"{role_id}.may_mutate[{index}] is invalid")
        for index, transition in enumerate(role.get("mediated_transitions", [])):
            require(isinstance(transition, dict) and set(transition) == {"transition", "mediated_by"}, f"{role_id}.mediated_transitions[{index}] has invalid shape")
            require(transition["mediated_by"] in entity_ids | role_ids, f"{role_id}.mediated_transitions[{index}] has unknown mediator")
        _unique_strings(role.get("forbidden_from", []), f"{role_id}.forbidden_from")
    queries = data.get("analysis_queries")
    require(isinstance(queries, dict) and queries, "analysis_queries must be a nonempty mapping")
    require(all(isinstance(value, str) and value.strip() for value in queries.values()), "analysis query descriptions must be nonempty")
    return data


def load_model(invariants: Path, environments: Path) -> tuple[dict[str, Any], dict[str, Any]]:
    catalog = parse_invariants(invariants)
    environment = validate_environment(load_yaml(environments), catalog)
    return catalog, environment


def candidates(catalog: dict[str, Any], environment: dict[str, Any]) -> dict[str, Any]:
    return {
        "status": "candidates_only",
        "semantic_authority": "AI judgment; human approval required for genuine contract changes",
        "invariant_candidates": [
            {"id": key, "owner_text": value["owner"], "condition_text": value["condition"],
             "causal_parent_text": value["causal_parent"]}
            for key, value in sorted(catalog["invariants"].items())
        ],
        "role_relation_candidates": [
            {"role": role_id, "relation": field, "target": target}
            for role_id, role in sorted(environment["roles"].items())
            for field in RELATION_LISTS for target in role.get(field, [])
        ],
        "analysis_intents": environment["analysis_queries"],
    }


def analyze(catalog: dict[str, Any], environment: dict[str, Any]) -> dict[str, Any]:
    owners = {target for role in environment["roles"].values() for target in role.get("owns", [])}
    consumers = {target for role in environment["roles"].values() for target in role.get("consumes", [])}
    emitted = {target for role in environment["roles"].values() for target in role.get("emits", [])}
    invoked = {target for role in environment["roles"].values() for target in role.get("may_invoke", [])}
    capability_ids = set(environment["entities"]["capabilities"])
    findings = []
    for target in sorted(emitted - owners - consumers):
        findings.append({"kind": "emitted_without_declared_owner_or_consumer", "target": target})
    for target in sorted(capability_ids - invoked):
        findings.append({"kind": "capability_not_invoked_by_baseline_role", "target": target})
    return {
        "status": "candidate_findings_only",
        "counts": {"invariants": len(catalog["invariants"]), "mechanisms": len(catalog["mechanisms"]),
                   "roles": len(environment["roles"]), "entities": sum(len(v) for v in environment["entities"].values())},
        "candidate_findings": findings,
        "semantic_queries": environment["analysis_queries"],
    }


def _node_id(value: str) -> str:
    return "N_" + re.sub(r"[^A-Za-z0-9_]", "_", value)


def _label(value: str) -> str:
    return value.replace('"', "'").replace("[", "(").replace("]", ")")


def _short_text(value: str, limit: int = 76) -> str:
    """Produce a stable display summary without creating a second semantic label."""
    plain = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", value)
    plain = re.sub(r"[`*_]", "", plain)
    plain = " ".join(plain.split())
    first_clause = re.split(r"[.;](?:\s|$)", plain, maxsplit=1)[0]
    if len(first_clause) <= limit:
        return first_clause
    shortened = first_clause[:limit - 1].rsplit(" ", 1)[0]
    return (shortened or first_clause[:limit - 1]) + "…"


def _invariant_style(classification: str) -> str:
    """Map the catalog's existing semantic class to an accessible color family."""
    value = classification.lower()
    if "security" in value:
        return "invSecurity"
    if "mutation" in value:
        return "invMutation"
    if "authority" in value:
        return "invAuthority"
    if "acceptance" in value:
        return "invAcceptance"
    if "truth" in value or "provenance" in value:
        return "invTruth"
    if "ownership" in value:
        return "invOwnership"
    if "independence" in value:
        return "invIndependence"
    if "interface" in value:
        return "invInterface"
    if "lifecycle" in value or "context" in value:
        return "invLifecycle"
    return "invDefault"


def _semantic_marker(style: str) -> str:
    emoji, label = STYLE_SEMANTICS[style]
    unbreakable_label = label.replace(" ", "\N{NO-BREAK SPACE}").replace(
        "/", "\N{WORD JOINER}/\N{WORD JOINER}",
    )
    return f"{emoji}\N{NO-BREAK SPACE}{unbreakable_label}"


def _markdown_cell(value: str) -> str:
    return " ".join(value.split()).replace("|", r"\|")


def _relation_rows(
    role: dict[str, Any], entity_labels: dict[str, str], invariant_styles: dict[str, str],
) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for field, relation in RELATION_LABELS.items():
        for target in role.get(field, []):
            if field == "bound_by":
                style = invariant_styles[target]
            elif field in {"owns", "emits"}:
                style = "owned"
            elif field in {"may_observe", "consumes"}:
                style = "observable"
            else:
                style = "capability"
            rows.append((relation, target, entity_labels.get(target, target), _semantic_marker(style)))
    for mutation in role.get("may_mutate", []):
        detail = f"{entity_labels.get(mutation['target'], mutation['target'])} (boundary: {mutation['boundary']})"
        rows.append(("MAY_MUTATE", mutation["target"], detail, _semantic_marker("invMutation")))
    for index, transition in enumerate(role.get("mediated_transitions", []), 1):
        detail = f"{transition['transition']} (via {transition['mediated_by']})"
        rows.append(("MEDIATED", f"transition-{index}", detail, _semantic_marker("transition")))
    for index, denial in enumerate(role.get("forbidden_from", []), 1):
        rows.append(("FORBIDDEN_FROM", f"deny-{index}", denial, _semantic_marker("forbidden")))
    return rows


def _role_table_lines(
    role: dict[str, Any], entity_labels: dict[str, str], invariant_styles: dict[str, str],
) -> list[str]:
    rows = _relation_rows(role, entity_labels, invariant_styles)
    lines = [
        "| Relation | Target | Label | Semantic class |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| `{relation}` | `{_markdown_cell(target)}` | {_markdown_cell(detail)} | {semantic} |"
        for relation, target, detail, semantic in rows
    )
    return lines


def _matrix_lines(
    environment: dict[str, Any], entity_labels: dict[str, str], invariant_styles: dict[str, str],
) -> list[str]:
    role_ids = sorted(environment["roles"])
    targets = sorted({
        target
        for role in environment["roles"].values()
        for field in RELATION_LABELS
        for target in role.get(field, [])
    })
    if not targets:
        return []
    role_labels = [_markdown_cell(environment["roles"][role_id]["label"]) for role_id in role_ids]
    lines = [
        "| Target | " + " | ".join(role_labels) + " |",
        "| --- | " + " | ".join("---" for _ in role_ids) + " |",
    ]
    for target in targets:
        cells = []
        for role_id in role_ids:
            role = environment["roles"][role_id]
            relations = [
                f"{_semantic_marker(invariant_styles[target] if field == 'bound_by' else ('owned' if field in {'owns', 'emits'} else 'observable' if field in {'may_observe', 'consumes'} else 'capability'))} {relation}"
                for field, relation in RELATION_LABELS.items()
                if target in role.get(field, [])
            ]
            cells.append(", ".join(relations))
        lines.append(
            f"| {_markdown_cell(entity_labels.get(target, target))} | "
            + " | ".join(cells) + " |"
        )
    return lines


def _role_slug(role: dict[str, Any]) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", role["label"].lower()).strip("-")
    require(bool(slug), f"role label cannot form a page name: {role['label']}")
    return slug


def _display_context(
    catalog: dict[str, Any], environment: dict[str, Any],
) -> tuple[dict[str, str], dict[str, str], dict[str, str], dict[str, str]]:
    entity_labels = {
        identifier: item["label"]
        for group in environment["entities"].values()
        for identifier, item in group.items()
    }
    invariant_labels = {
        identifier: _short_text(item["condition"])
        for identifier, item in catalog["invariants"].items()
    }
    invariant_styles = {
        identifier: _invariant_style(item["class"])
        for identifier, item in catalog["invariants"].items()
    }
    return entity_labels, invariant_labels, invariant_styles, {**entity_labels, **invariant_labels}


def _role_graph_lines(
    role_id: str, role: dict[str, Any],
    entity_labels: dict[str, str], invariant_labels: dict[str, str],
    invariant_styles: dict[str, str],
) -> list[str]:
    lines = [
        "```mermaid", "flowchart TB", *MERMAID_CLASS_DEFS,
        f"  R[\"{_label(role['label'])}\"]", "  class R role",
    ]
    previous_tail: str | None = None
    groups = [
        ("Pinned structure", "BOUND_BY", [
            (item, f"{item}<br/>{invariant_labels[item]}", invariant_styles[item])
            for item in role.get("bound_by", [])
        ]),
        ("Capabilities", "MAY_INVOKE", [
            (item, entity_labels[item], "capability") for item in role.get("may_invoke", [])
        ]),
        ("Owned state and artifacts", "OWNS", [
            (item, entity_labels[item], "owned") for item in role.get("owns", [])
        ]),
        ("Observable inputs", "MAY_OBSERVE", [
            (item, entity_labels[item], "observable") for item in role.get("may_observe", [])
        ]),
        ("Explicit non-authority", "FORBIDDEN_FROM", [
            (f"deny-{index}", value, "forbidden")
            for index, value in enumerate(role.get("forbidden_from", []), 1)
        ]),
    ]
    for number, (title, relation, items) in enumerate(groups, 1):
        if not items:
            continue
        lines.append(f"  subgraph G{number}[\"{title}\"]")
        lines.append("    direction TB")
        nodes = []
        for identifier, label, style in items:
            node = _node_id(f"{role_id}-{number}-{identifier}")
            nodes.append(node)
            lines.append(f"    {node}[\"{_label(label)}\"]")
            lines.append(f"    class {node} {style}")
        for earlier, later in zip(nodes, nodes[1:]):
            lines.append(f"    {earlier} ~~~ {later}")
        lines.append("  end")
        if previous_tail is not None:
            lines.append(f"  {previous_tail} ~~~ {nodes[0]}")
        previous_tail = nodes[-1]
        lines.append(f"  R -->|{relation}| {nodes[0]}")
    for index, transition in enumerate(role.get("mediated_transitions", []), 1):
        node = _node_id(role_id + '-transition-' + str(index))
        if previous_tail is not None:
            lines.append(f"  {previous_tail} ~~~ {node}")
        previous_tail = node
        lines += [
            f"  {node}[\"{_label(transition['transition'])}\"]",
            f"  class {node} transition",
            f"  R -.->|MEDIATED_BY {transition['mediated_by']}| {node}",
        ]
    lines.append("```")
    return lines


def render(catalog: dict[str, Any], environment: dict[str, Any], invariant_path: Path, environment_path: Path) -> str:
    inv_digest = hashlib.sha256(invariant_path.read_bytes()).hexdigest()
    env_digest = hashlib.sha256(environment_path.read_bytes()).hexdigest()
    lines = [
        "# Agent Environment Graphs", "",
        GENERATED_COMMENT,
        f"<!-- invariant-sha256: {inv_digest} -->", f"<!-- environment-sha256: {env_digest} -->", "",
        "This is a deterministic view of [`agent-environments.yaml`](agent-environments.yaml).",
        "Invariant and machinery truth remains owned by [`workflow-invariants.md`](workflow-invariants.md);",
        "role projection truth remains owned by the YAML input. Edit those owners and regenerate this view.", "",
        "Analysis produced by the CLI is candidate evidence only. Semantic classification and genuine contract changes",
        "remain AI-judged and human-authorized respectively.", "",
        "The diagrams use one visible entry edge per relation group to avoid unreadable fan-out; the relation tables",
        "below them enumerate every individual edge. Invariant node text is a shortened view of the catalog condition.", "",
        "Color uses the same basic GitHub circle families in diagrams and tables. Text remains beside every marker",
        "so semantic meaning does not depend on color alone.", "",
    ]
    lines += _legend_lines()
    entity_labels, invariant_labels, invariant_styles, display_labels = _display_context(catalog, environment)
    for role_id, role in environment["roles"].items():
        lines += [f"## {role['label']}", ""]
        lines += _role_graph_lines(
            role_id, role, entity_labels, invariant_labels, invariant_styles,
        )
        lines += ["", role["objective"].strip(), ""]
        table = _role_table_lines(role, display_labels, invariant_styles)
        if table:
            lines += ["#### Relation table", ""] + table + [""]
    matrix = _matrix_lines(environment, display_labels, invariant_styles)
    if matrix:
        lines += [
            "## Role × relation matrix", "",
            "Every target this environment references, and which relation each role holds to it.", "",
        ]
        lines += matrix + [""]
    summary = analyze(catalog, environment)
    lines += ["## Deterministic baseline summary", "", f"- Invariants: {summary['counts']['invariants']}",
              f"- Mechanisms: {summary['counts']['mechanisms']}", f"- Roles: {summary['counts']['roles']}",
              f"- States, artifacts, and capabilities: {summary['counts']['entities']}",
              f"- Candidate structural findings: {len(summary['candidate_findings'])}", ""]
    return "\n".join(lines)


def _provenance_lines(invariant_path: Path, environment_path: Path) -> list[str]:
    return [
        GENERATED_COMMENT,
        f"<!-- invariant-sha256: {hashlib.sha256(invariant_path.read_bytes()).hexdigest()} -->",
        f"<!-- environment-sha256: {hashlib.sha256(environment_path.read_bytes()).hexdigest()} -->",
    ]


def _source_hashes(invariant_path: Path, environment_path: Path) -> dict[str, dict[str, str]]:
    return {
        "invariant_catalog": {
            "path": "../workflow-invariants.md",
            "sha256": hashlib.sha256(invariant_path.read_bytes()).hexdigest(),
        },
        "role_environment": {
            "path": "../agent-environments.yaml",
            "sha256": hashlib.sha256(environment_path.read_bytes()).hexdigest(),
        },
    }


def _legend_lines() -> list[str]:
    return [
        "## Color legend", "",
        "| Marker | Semantic meaning |",
        "| --- | --- |",
        "| ⚫\N{NO-BREAK SPACE}black | Role identity or unclassified item |",
        "| 🟡\N{NO-BREAK SPACE}yellow | Authority |",
        "| 🟣\N{NO-BREAK SPACE}purple | Ownership or independence |",
        "| 🔴\N{NO-BREAK SPACE}red | Mutation, security, or prohibition |",
        "| 🟢\N{NO-BREAK SPACE}green | Acceptance, ownership, or emitted output |",
        "| 🔵\N{NO-BREAK SPACE}blue | Interface, capability, observation, or consumed input |",
        "| 🟤\N{NO-BREAK SPACE}brown | Truth or provenance |",
        "| ⚪\N{NO-BREAK SPACE}white | Lifecycle or context |",
        "| 🟠\N{NO-BREAK SPACE}orange | Mediated transition |", "",
    ]


def render_overview(
    catalog: dict[str, Any], environment: dict[str, Any],
    invariant_path: Path, environment_path: Path,
) -> str:
    _, _, invariant_styles, display_labels = _display_context(catalog, environment)
    lines = ["# Agent Environment Graphs", "", *_provenance_lines(invariant_path, environment_path), ""]
    lines += [
        "This is the overall generated view of [`agent-environments.yaml`](agent-environments.yaml).",
        "Invariant and machinery truth remains owned by [`workflow-invariants.md`](workflow-invariants.md);",
        "role projection truth remains owned by the YAML input. Individual role pages are generated views.", "",
        "## Role directory", "",
        "The [role-view index](agent-environment-views/README.md) provides GitHub directory navigation.", "",
        "| Role | Objective | Pinned invariants | Capabilities | Detail |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    slugs: set[str] = set()
    for role in environment["roles"].values():
        slug = _role_slug(role)
        require(slug not in slugs, f"duplicate role page slug: {slug}")
        slugs.add(slug)
        lines.append(
            f"| {role['label']} | {_markdown_cell(role['objective'])} | {len(role.get('bound_by', []))} | "
            f"{len(role.get('may_invoke', []))} | [Open role view](agent-environment-views/{slug}.md) |"
        )
    lines += [""] + _legend_lines()
    matrix = _matrix_lines(environment, display_labels, invariant_styles)
    if matrix:
        lines += [
            "## Role × relation matrix", "",
            "Every target referenced by the baseline role environment and each role's declared relation to it.", "",
            *matrix, "",
        ]
    summary = analyze(catalog, environment)
    lines += [
        "## Deterministic baseline summary", "",
        f"- Invariants: {summary['counts']['invariants']}",
        f"- Mechanisms: {summary['counts']['mechanisms']}",
        f"- Roles: {summary['counts']['roles']}",
        f"- States, artifacts, and capabilities: {summary['counts']['entities']}",
        f"- Candidate structural findings: {len(summary['candidate_findings'])}", "",
    ]
    if summary["candidate_findings"]:
        lines += ["### Candidate structural findings", ""]
        lines += [
            f"- `{item['kind']}`: `{item['target']}`"
            for item in summary["candidate_findings"]
        ] + [""]
    return "\n".join(lines)


def render_role_index(
    catalog: dict[str, Any], environment: dict[str, Any],
    invariant_path: Path, environment_path: Path,
) -> str:
    lines = ["# Agent Environment Role Views", "", *_provenance_lines(invariant_path, environment_path), ""]
    lines += [
        "Generated navigation for the role-scoped projections in this directory.",
        "See the [overall environment view](../agent-environment-graphs.md) for the shared legend,",
        "cross-role matrix, and deterministic baseline summary.", "",
        "| Role | Objective | Context lifetime | Detail | Analysis input |",
        "| --- | --- | --- | --- | --- |",
    ]
    for role in environment["roles"].values():
        slug = _role_slug(role)
        lines.append(
            f"| {role['label']} | {_markdown_cell(role['objective'])} | "
            f"{_markdown_cell(role['context_lifetime'])} | [Open](./{slug}.md) | "
            f"[YAML](./{slug}.yaml) |"
        )
    lines += [
        "", "These pages are deterministic projections, not editable contract owners. Update",
        "[`../agent-environments.yaml`](../agent-environments.yaml) or",
        "[`../workflow-invariants.md`](../workflow-invariants.md) and regenerate the page set.", "",
    ]
    return "\n".join(lines)


def _detail_rows(role: dict[str, Any], entity_labels: dict[str, str]) -> list[str]:
    lines: list[str] = []
    observation_limits = role.get("observation_limits", {})
    if observation_limits:
        lines += ["## Observation limits", "", "| Target | Visible projection |", "| --- | --- |"]
        lines += [
            f"| `{target}` ({_markdown_cell(entity_labels.get(target, target))}) | {_markdown_cell(limit)} |"
            for target, limit in observation_limits.items()
        ] + [""]
    mutations = role.get("may_mutate", [])
    if mutations:
        lines += ["## Mutation boundaries", "", "| Target | Authorized boundary |", "| --- | --- |"]
        lines += [
            f"| `{item['target']}` ({_markdown_cell(entity_labels[item['target']])}) | "
            f"{_markdown_cell(item['boundary'])} |"
            for item in mutations
        ] + [""]
    transitions = role.get("mediated_transitions", [])
    if transitions:
        lines += ["## Mediated transitions", "", "| Transition | Mediated by |", "| --- | --- |"]
        lines += [
            f"| {_markdown_cell(item['transition'])} | `{item['mediated_by']}` |"
            for item in transitions
        ] + [""]
    independence = role.get("independence", {})
    if independence:
        lines += ["## Independence boundary", "", "| Constraint | Value |", "| --- | --- |"]
        for field, value in independence.items():
            values = value if isinstance(value, list) else [value]
            rendered = "<br/>".join(_markdown_cell(str(item)) for item in values)
            lines.append(f"| `{field}` | {rendered} |")
        lines.append("")
    denials = role.get("forbidden_from", [])
    if denials:
        lines += ["## Explicit non-authority", ""]
        lines += [f"- {_markdown_cell(item)}" for item in denials] + [""]
    return lines


def render_role_page(
    catalog: dict[str, Any], environment: dict[str, Any], role_id: str,
    invariant_path: Path, environment_path: Path,
) -> str:
    role = environment["roles"][role_id]
    slug = _role_slug(role)
    entity_labels, invariant_labels, invariant_styles, display_labels = _display_context(catalog, environment)
    role_contract = environment.get("sources", {}).get("role_contracts", {}).get(role_id)
    lines = [f"# {role['label']} Environment", "", *_provenance_lines(invariant_path, environment_path), ""]
    lines += [
        "[← Overall environment](../agent-environment-graphs.md) · "
        "[Role index](./README.md) · [Invariant catalog](../workflow-invariants.md) · "
        f"[Lossless YAML projection](./{slug}.yaml)", "",
        "This page is a generated role-scoped projection. Its graph is an overview; the relation table is the",
        "complete declared edge ledger for this role.", "",
        "## Role contract", "",
        "| Field | Value |", "| --- | --- |",
        f"| Role ID | `{role_id}` |",
        f"| Objective | {_markdown_cell(role['objective'])} |",
        f"| Context lifetime | {_markdown_cell(role['context_lifetime'])} |",
    ]
    if role_contract:
        lines.append(f"| Owning role contract | [`{role_contract}`](../../{role_contract}) |")
    lines += [
        "", "## At a glance", "",
        "| Pinned invariants | Capabilities | Observes | Mutates | Owns | Emits | Prohibitions |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        f"| {len(role.get('bound_by', []))} | {len(role.get('may_invoke', []))} | "
        f"{len(role.get('may_observe', []))} | {len(role.get('may_mutate', []))} | "
        f"{len(role.get('owns', []))} | {len(role.get('emits', []))} | "
        f"{len(role.get('forbidden_from', []))} |", "",
        "Semantic colors are defined once in the [shared legend](../agent-environment-graphs.md#color-legend).", "",
        "## Environment graph", "",
    ]
    lines += _role_graph_lines(role_id, role, entity_labels, invariant_labels, invariant_styles)
    lines += ["", "## Complete relation table", ""]
    lines += _role_table_lines(role, display_labels, invariant_styles) + [""]
    must_require = role.get("must_require", {})
    if must_require:
        lines += [
            "## Required consequences from other roles", "",
            "| Required role | Invariant consequence |", "| --- | --- |",
        ]
        for target_role, invariant_ids in must_require.items():
            target_label = environment["roles"][target_role]["label"]
            for invariant_id in invariant_ids:
                lines.append(f"| {target_label} | `{invariant_id}` — {invariant_labels[invariant_id]} |")
        lines.append("")
    lines += _detail_rows(role, entity_labels)
    return "\n".join(lines)


def _referenced_entity_ids(role: dict[str, Any], environment: dict[str, Any]) -> set[str]:
    entity_ids = {
        identifier
        for group in environment["entities"].values()
        for identifier in group
    }
    referenced = {
        target
        for field in RELATION_LISTS
        if field != "bound_by"
        for target in role.get(field, [])
    }
    referenced.update(role.get("observation_limits", {}))
    referenced.update(item["target"] for item in role.get("may_mutate", []))
    referenced.update(
        item["mediated_by"]
        for item in role.get("mediated_transitions", [])
        if item["mediated_by"] in entity_ids
    )
    return referenced


def _direct_invariant_ids(role: dict[str, Any]) -> list[str]:
    identifiers = set(role.get("bound_by", []))
    identifiers.update(
        invariant_id
        for invariant_ids in role.get("must_require", {}).values()
        for invariant_id in invariant_ids
    )
    return sorted(identifiers)


def _referenced_invariant_ids(role: dict[str, Any], catalog: dict[str, Any]) -> list[str]:
    identifiers = set(_direct_invariant_ids(role))
    pending = list(identifiers)
    while pending:
        identifier = pending.pop()
        for related in catalog["invariants"][identifier]["relations"]:
            if related not in identifiers:
                identifiers.add(related)
                pending.append(related)
    return sorted(identifiers)


def render_role_yaml(
    catalog: dict[str, Any], environment: dict[str, Any], role_id: str,
    invariant_path: Path, environment_path: Path,
) -> str:
    """Render a lossless role-scoped analysis projection from both canonical inputs."""
    role = environment["roles"][role_id]
    referenced_entities = _referenced_entity_ids(role, environment)
    entities = {
        kind: {
            identifier: item
            for identifier, item in mapping.items()
            if identifier in referenced_entities
        }
        for kind, mapping in environment["entities"].items()
    }
    direct_invariant_ids = _direct_invariant_ids(role)
    invariant_ids = _referenced_invariant_ids(role, catalog)
    invariants = {
        identifier: catalog["invariants"][identifier]
        for identifier in invariant_ids
    }
    mechanism_ids = {
        mechanism
        for invariant in invariants.values()
        for mechanism in invariant["mechanisms"]
    }
    mechanism_ids.update(
        item["mechanism"]
        for mapping in entities.values()
        for item in mapping.values()
        if "mechanism" in item
    )
    referenced_role_ids = set(role.get("must_require", {}))
    referenced_role_ids.update(
        item["mediated_by"]
        for item in role.get("mediated_transitions", [])
        if item["mediated_by"] in environment["roles"]
    )
    projection = {
        "schema_version": 1,
        "document_id": f"{environment['document_id']}.{role_id}.projection",
        "status": "generated_projection",
        "generated_by": "skills/agent-environment-graph/scripts/agent_environment_graph.py",
        "source_inputs": _source_hashes(invariant_path, environment_path),
        "environment_context": {
            field: environment[field]
            for field in ("document_id", "status", "verified_on", "scope", "sources", "semantics", "analysis_queries")
            if field in environment
        },
        "role_id": role_id,
        "role": role,
        "direct_invariant_ids": direct_invariant_ids,
        "referenced_roles": {
            identifier: {
                field: environment["roles"][identifier][field]
                for field in ("label", "objective", "context_lifetime")
            }
            for identifier in sorted(referenced_role_ids)
        },
        "entities": entities,
        "invariants": invariants,
        "mechanisms": {
            identifier: catalog["mechanisms"][identifier]
            for identifier in sorted(mechanism_ids)
        },
    }
    return GENERATED_YAML_COMMENT + "\n" + yaml.safe_dump(
        projection, sort_keys=False, allow_unicode=True, width=100,
    )


def render_site(
    catalog: dict[str, Any], environment: dict[str, Any],
    invariant_path: Path, environment_path: Path,
) -> tuple[str, dict[str, str]]:
    pages = {"README.md": render_role_index(catalog, environment, invariant_path, environment_path)}
    for role_id, role in environment["roles"].items():
        slug = _role_slug(role)
        markdown_filename = slug + ".md"
        yaml_filename = slug + ".yaml"
        require(markdown_filename not in pages and yaml_filename not in pages, f"duplicate role page slug: {slug}")
        pages[markdown_filename] = render_role_page(catalog, environment, role_id, invariant_path, environment_path)
        pages[yaml_filename] = render_role_yaml(catalog, environment, role_id, invariant_path, environment_path)
    return render_overview(catalog, environment, invariant_path, environment_path), pages


def _is_generated_artifact(path: Path) -> bool:
    try:
        source = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    return GENERATED_COMMENT in source or GENERATED_YAML_COMMENT in source


def write_site(output: Path, role_output_dir: Path, overview: str, pages: dict[str, str]) -> list[str]:
    output.parent.mkdir(parents=True, exist_ok=True)
    role_output_dir.mkdir(parents=True, exist_ok=True)
    output.write_text(overview, encoding="utf-8")
    for filename, content in pages.items():
        (role_output_dir / filename).write_text(content, encoding="utf-8")
    removed: list[str] = []
    for candidate in sorted(role_output_dir.iterdir()):
        if candidate.suffix not in {".md", ".yaml"}:
            continue
        if candidate.name in pages:
            continue
        if _is_generated_artifact(candidate):
            candidate.unlink()
            removed.append(str(candidate))
    return removed


def check_site(output: Path, role_output_dir: Path, overview: str, pages: dict[str, str]) -> None:
    require(output.read_text(encoding="utf-8") == overview, f"rendered view is stale: {output}")
    require(role_output_dir.is_dir(), f"missing role output directory: {role_output_dir}")
    for filename, content in pages.items():
        path = role_output_dir / filename
        require(path.is_file(), f"missing generated role page: {path}")
        require(path.read_text(encoding="utf-8") == content, f"generated role page is stale: {path}")
    expected = set(pages)
    unexpected = sorted(
        path.name
        for path in role_output_dir.iterdir()
        if path.suffix in {".md", ".yaml"}
        and path.name not in expected
        and _is_generated_artifact(path)
    )
    require(not unexpected, f"unexpected generated role artifacts: {', '.join(unexpected)}")


def validate_judgments(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    require(isinstance(data, dict) and set(data) == {"schema_version", "producer", "judgments"}, "judgment artifact has invalid fields")
    require(data["schema_version"] == 1, "judgment schema_version must be 1")
    require(isinstance(data["producer"], str) and data["producer"].strip(), "judgment producer is required")
    judgments = data["judgments"]
    require(isinstance(judgments, list), "judgments must be a list")
    ids = set()
    required = {"id", "category", "subject", "conclusion", "evidence", "changes_contract", "human_approval"}
    for index, item in enumerate(judgments):
        require(isinstance(item, dict) and set(item) == required, f"judgments[{index}] has invalid fields")
        require(isinstance(item["id"], str) and item["id"] not in ids, f"judgments[{index}].id is missing or duplicate")
        ids.add(item["id"])
        require(item["category"] in SEMANTIC_CATEGORIES, f"judgments[{index}].category is unsupported")
        for field in ("subject", "conclusion"):
            require(isinstance(item[field], str) and item[field].strip(), f"judgments[{index}].{field} is required")
        _unique_strings(item["evidence"], f"judgments[{index}].evidence")
        require(bool(item["evidence"]), f"judgments[{index}].evidence must not be empty")
        require(isinstance(item["changes_contract"], bool), f"judgments[{index}].changes_contract must be boolean")
        if item["changes_contract"]:
            approval = item["human_approval"]
            require(isinstance(approval, dict) and set(approval) == {"approver", "reference"}, f"judgments[{index}] contract change requires human approval")
            require(all(isinstance(value, str) and value.strip() for value in approval.values()), f"judgments[{index}] approval is incomplete")
        else:
            require(item["human_approval"] is None, f"judgments[{index}] non-contract judgment must not claim approval")
    return {"status": "valid", "judgments": len(judgments)}


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser()
    sub = result.add_subparsers(dest="command", required=True)
    for name in ("validate", "candidates", "analyze", "render", "check"):
        command = sub.add_parser(name)
        command.add_argument("--invariants", type=Path, required=True)
        command.add_argument("--environments", type=Path, required=True)
        if name == "render":
            command.add_argument("--output", type=Path, required=True)
            command.add_argument("--role-output-dir", type=Path, required=True)
        if name == "check":
            command.add_argument("--rendered", type=Path, required=True)
            command.add_argument("--role-output-dir", type=Path, required=True)
    judgments = sub.add_parser("validate-judgments")
    judgments.add_argument("path", type=Path)
    return result


def main() -> int:
    arguments = parser().parse_args()
    try:
        if arguments.command == "validate-judgments":
            result = validate_judgments(arguments.path)
        else:
            catalog, environment = load_model(arguments.invariants, arguments.environments)
            if arguments.command == "validate": result = {"status": "valid", **analyze(catalog, environment)["counts"]}
            elif arguments.command == "candidates": result = candidates(catalog, environment)
            elif arguments.command == "analyze": result = analyze(catalog, environment)
            else:
                overview, pages = render_site(catalog, environment, arguments.invariants, arguments.environments)
                if arguments.command == "render":
                    removed = write_site(arguments.output, arguments.role_output_dir, overview, pages)
                    result = {
                        "status": "rendered", "output": str(arguments.output),
                        "role_output_dir": str(arguments.role_output_dir),
                        "role_pages": sorted(pages), "removed_stale_pages": removed,
                    }
                else:
                    check_site(arguments.rendered, arguments.role_output_dir, overview, pages)
                    result = {
                        "status": "current", "rendered": str(arguments.rendered),
                        "role_output_dir": str(arguments.role_output_dir),
                        "role_pages": sorted(pages),
                    }
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    except (GraphError, OSError, json.JSONDecodeError) as error:
        print(json.dumps({"status": "invalid", "error": str(error)}, sort_keys=True), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
