import { ChromeEndpoint, selectTarget } from "./chrome-endpoint.mjs";
import { CdpSession } from "./cdp-session.mjs";
import { ArtifactStore } from "./artifact-store.mjs";
import { evaluate, documentObservationExpression, domActionExpression } from "./operations.mjs";
import { validateObservation } from "./schema-validation.mjs";
const DEFAULT_LIMITS = { events: 100, textBytes: 64000, evidenceBytes: 64000, artifacts: 20, endpointTimeoutMs: 5000 };
function truncateUtf8(value, bytes) { const encoded = Buffer.from(value); if (encoded.length <= bytes) return value; let end = bytes; while (end && (encoded[end] & 0xc0) === 0x80) end -= 1; return encoded.subarray(0, end).toString(); }
export class ChromeVisionBroker {
  constructor(config) { if (config?.version !== 1) throw new Error("Chrome Vision config version 1 is required"); this.config = config; this.limits = { ...DEFAULT_LIMITS, ...config.limits }; this.endpoint = new ChromeEndpoint(config.endpoint, this.limits.endpointTimeoutMs); this.sessions = new Map(); this.artifacts = new ArtifactStore(config.artifactDirectory || "tmp/chrome-vision", this.limits.artifacts); }
  packet(operation, evidence, session = null, { limitations = [], artifacts = [], inputs = {}, mechanism = operation } = {}) { const packet={ schemaVersion: 1, operation, observedAt: new Date().toISOString(), epochs: session ? { ...session.epochs } : { target: 0, session: 0, document: 0 }, evidence, artifacts, limitations, provenance: { mechanism, inputs }, health: session ? session.health() : { connected: false, pendingCalls: 0, queuedEvents: 0 } }; const validation=validateObservation(packet); if(!validation.valid)throw new Error(`Chrome Vision produced an invalid observation packet: ${validation.errors.join("; ")}`); return packet; }
  async attach(alias, matcher) { const targets = await this.endpoint.listTargets(); const target = selectTarget(targets, matcher || this.config.targetAliases?.[alias]); if (!target?.webSocketDebuggerUrl) throw new Error(`No attachable Chrome target matched ${alias || "request"}`); const previous = this.sessions.get(alias); if (previous && previous.webSocketUrl !== target.webSocketDebuggerUrl) previous.markTargetReplacement(target.webSocketDebuggerUrl); const session = previous || new CdpSession(target.webSocketDebuggerUrl, { eventLimit: this.limits.events }); if (previous) await previous.reconnect(); else await session.ready; this.sessions.set(alias, session); return { target, session }; }
  async request(request) {
    const operation = request.operation;
    if (operation === "chrome.targets.list") { const targets = await this.endpoint.listTargets(); return this.packet(operation, targets.slice(0, 100), null, { limitations: targets.length > 100 ? ["target list truncated to 100"] : [], inputs: { endpoint: this.config.endpoint }, mechanism: "Chrome /json/list" }); }
    const alias = request.targetAlias || "default"; let session = this.sessions.get(alias); let target;
    if (!session || request.reattach) ({ target, session } = await this.attach(alias, request.matcher));
    if (operation === "chrome.health") return this.packet(operation, session.health(), session, { inputs: { targetAlias: alias }, mechanism: "broker session state" });
    if (operation === "chrome.document.observe") { const observed = await evaluate(session, documentObservationExpression); const raw = Buffer.from(observed.text || ""); const truncated = raw.length > this.limits.textBytes; observed.text = truncateUtf8(observed.text || "", this.limits.textBytes); return this.packet(operation, observed, session, { limitations: truncated ? [`document text truncated to ${this.limits.textBytes} bytes at a UTF-8 boundary`] : [], inputs: { targetAlias: alias, fields: ["url","title","readyState","lang","text"] }, mechanism: "Runtime.evaluate document observation" }); }
    if (operation === "chrome.page.captureScreenshot") { const result = await session.call("Page.captureScreenshot", { format: request.format || "png", fromSurface: true }); const artifact = await this.artifacts.write(request.name || `screenshot-${Date.now()}.png`, Buffer.from(result.data, "base64"), "image/png"); return this.packet(operation, { captured: !artifact.omitted }, session, { artifacts: artifact.omitted ? [] : [artifact], limitations: artifact.limitation ? [artifact.limitation] : [], inputs: { targetAlias: alias, format: request.format || "png" }, mechanism: "Page.captureScreenshot" }); }
    if (operation === "chrome.dom.click" || operation === "chrome.dom.fill") { const kind = operation.endsWith("click") ? "click" : "fill"; const result = await evaluate(session, domActionExpression(kind, request.selector, request.value), 20000, { userGesture: kind === "click" }); return this.packet(operation, result, session, { inputs: { targetAlias: alias, selector: request.selector, ...(kind === "fill" ? { value: request.value } : {}) }, mechanism: "Runtime.evaluate DOM interaction" }); }
    if (operation === "chrome.runtime.evaluate") { const result = await evaluate(session, request.expression, request.timeout); return this.packet(operation, result, session, { inputs: { targetAlias: alias, expression: request.expression }, mechanism: "Runtime.evaluate" }); }
    if (operation === "chrome.extensions.openSidePanel") { const expression = `chrome.sidePanel.open({tabId:${JSON.stringify(request.tabId)}})`; const result = await evaluate(session, expression, request.timeout, { userGesture: true }); return this.packet(operation, result ?? null, session, { inputs: { targetAlias: alias, tabId: request.tabId }, mechanism: "Runtime.evaluate chrome.sidePanel.open" }); }
    if (operation === "cdp.call") { const result = await session.call(request.method, request.params || {}, request.timeout); const serialized=Buffer.from(JSON.stringify(result)); if(serialized.length<=this.limits.evidenceBytes)return this.packet(operation,result,session,{inputs:{targetAlias:alias,method:request.method,params:request.params||{}},mechanism:request.method}); const artifact=await this.artifacts.write(`cdp-${Date.now()}.json`,serialized,"application/json"); return this.packet(operation,{artifactBacked:!artifact.omitted,bytes:serialized.length},session,{artifacts:artifact.omitted?[]:[artifact],limitations:[artifact.limitation||`CDP response exceeded ${this.limits.evidenceBytes} evidence bytes and was moved to an artifact`],inputs:{targetAlias:alias,method:request.method,params:request.params||{}},mechanism:request.method}); }
    throw new Error(`Unsupported Chrome Vision operation: ${operation}`);
  }
}
